import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";

export const metadata: Metadata = {
  title: "HR Solutions",
  description: "Generated by HR Solutions",
  icons: {
    icon: [
      { url: "/icon.png?v=20260330-2", type: "image/png", sizes: "32x32" },
      { url: "/icon.png?v=20260330-2", type: "image/png", sizes: "192x192" },
    ],
    shortcut: [{ url: "/icon.png?v=20260330-2", type: "image/png" }],
    apple: [{ url: "/icon.png?v=20260330-2", type: "image/png", sizes: "180x180" }],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
